name = "englishgame-fun"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["GameRoom"]

[[d1_databases]]
binding = "DB"
database_name = "englishgame-db"
database_id = "3095572a-f17a-47e2-bfb1-b71eb4b925c5"

[vars]
ENVIRONMENT = "development"
